version: "3.9"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    restart: unless-stopped
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCKER_BOX}/traefik/data/traefik.yml:/traefik.yml:ro
      - ${DOCKER_BOX}/traefik/data/config.yml:/config.yml
      - ${DOCKER_BOX}/traefik/data/letsencrypt:/letsencrypt
      - ${DOCKER_BOX}/traefik/data/traefik.log:/traefik.log
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CF_API_EMAIL=${CF_EMAIL}
      - CF_API_KEY=${CF_APIKEY}
    labels:
      - traefik.enable=true
      - trafik.docker.network=traefik-proxy
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}
      - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}
      - traefik.http.routers.traefik.service=api@internal

networks:
  traefik-proxy:
    external: true
